# Auto-generated by release CI (yufeng-kano/kano-proxy) — do not edit by hand.
class KanoProxy < Formula
  desc "Official kano-proxy CLI: expose local LLM servers as providers"
  homepage "https://github.com/yufeng-kano/kano-proxy"
  version "4.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yufeng-kano/kano-proxy/releases/download/v4.4.1/kano-proxy-4.4.1-aarch64-apple-darwin.tar.gz"
      sha256 "8fc2456b6ab48e791c0c0f2b8e6bf884fc6c6acd6011634e3bdab6a20beade38"
    else
      url "https://github.com/yufeng-kano/kano-proxy/releases/download/v4.4.1/kano-proxy-4.4.1-x86_64-apple-darwin.tar.gz"
      sha256 "55d23b3a83559a645f6efd88ce0d4d08fa0d7db75ff5ebefb5978ddb0cf58644"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/yufeng-kano/kano-proxy/releases/download/v4.4.1/kano-proxy-4.4.1-aarch64-unknown-linux-musl.tar.gz"
      sha256 "52bdbde6817f9740bc7b1f757297b94eba69968566c61a9d4e33e4eacc45ab6b"
    else
      url "https://github.com/yufeng-kano/kano-proxy/releases/download/v4.4.1/kano-proxy-4.4.1-x86_64-unknown-linux-musl.tar.gz"
      sha256 "4830deb1473b1e0a9f08c574e15ad7a2d619f7b3196ac433c825e8f6fa118c2b"
    end
  end

  def install
    bin.install "kano-proxy"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kano-proxy --version")
  end
end
