# Auto-generated by release CI (yufeng-kano/kano-proxy) — do not edit by hand.
class KanoProxy < Formula
  desc "Official kano-proxy CLI: expose local LLM servers as providers"
  homepage "https://github.com/yufeng-kano/kano-proxy"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yufeng-kano/kano-proxy/releases/download/cli-v1.0.0/kano-proxy-1.0.0-aarch64-apple-darwin.tar.gz"
      sha256 "3e4b7ff4bc7ae2c5bfab79e9a77a85b207409cad7af51d3812858abd9bb0a761"
    else
      url "https://github.com/yufeng-kano/kano-proxy/releases/download/cli-v1.0.0/kano-proxy-1.0.0-x86_64-apple-darwin.tar.gz"
      sha256 "13baa6a6596353af377f726f40265ea89aa7b24d95b3bd720f9b58099644a0d7"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/yufeng-kano/kano-proxy/releases/download/cli-v1.0.0/kano-proxy-1.0.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "38130e60bfc346bacdfed047818dd635ff8b9d609d3d467d1f335d5efc9973eb"
    else
      url "https://github.com/yufeng-kano/kano-proxy/releases/download/cli-v1.0.0/kano-proxy-1.0.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "3f5049549c8011a5677102a2ccc4de587fd7e4ae5ade8785fd8d77c31ee72c9e"
    end
  end

  def install
    bin.install "kano-proxy"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kano-proxy --version")
  end
end
