# Auto-generated by release CI (yufeng-kano/kano-proxy) — do not edit by hand.
class KanoProxy < Formula
  desc "Official kano-proxy CLI: expose local LLM servers as providers"
  homepage "https://github.com/yufeng-kano/kano-proxy"
  version "4.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yufeng-kano/kano-proxy/releases/download/v4.5.0/kano-proxy-4.5.0-aarch64-apple-darwin.tar.gz"
      sha256 "4e45bb57793324641c502aaf5205e48f92eadf561163b23458c5e3370733dca5"
    else
      url "https://github.com/yufeng-kano/kano-proxy/releases/download/v4.5.0/kano-proxy-4.5.0-x86_64-apple-darwin.tar.gz"
      sha256 "ed10a4a9cdc34517dd0a7f24bc4039c1e78207c07bab89a586334843357d8404"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/yufeng-kano/kano-proxy/releases/download/v4.5.0/kano-proxy-4.5.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "3b83ae401adc21cc69df15b2886a24de74c3c1233d56c9c54e4cfa6543cdb57f"
    else
      url "https://github.com/yufeng-kano/kano-proxy/releases/download/v4.5.0/kano-proxy-4.5.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "5efc446e9dd3f9bd6de6edf1bee1375992366ed385cd6fcc40db952f9e55b75d"
    end
  end

  def install
    bin.install "kano-proxy"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kano-proxy --version")
  end
end
